environment:
  cookie_root_domain: .o6s.io
  external_domain: https://JacquesFr.o6s.io
  external_redirect_domain: https://JacquesFr.o6s.io/auth
  gateway: https://JacquesFr.o6s.io
  origin: https://JacquesFr.o6s.io
  web_domain: https://JacquesFr.o6s.io
  websocket_server_url: https://dzn-sandbox.herokuapp.com
